### ISSUE TITLE
Home Page Art to-do list

### ISSUE THREAD

**Issue by Luke-Michael-Brown** [pfryerda/symbolize-android#1]
- [ ] Make home page animation
- [ ] Make homepage background
- [ ] Make settings dialog ( shared with game and levels )
- [ ] Make mute button
