### ISSUE TITLE
Game Page Art to-do list

### ISSUE THREAD

**Issue by Luke-Michael-Brown** [pfryerda/symbolize-android#3]
There is lots of overlap between levels page and game page, since a level page 'is-a' game page.

- [ ] Make gradient background ( shared by level and game page )
- [ ] Make game page text pretty ( shared with level page )
- [ ] Make hints dialog ( shared with levels )
- [ ] Make settings dialog ( shared with game and levels )
- [ ] Make check solution dialog ( shared with game page )
- [ ] Make button art ( some overlap with levels page )
    - [ ] Levels button
    - [ ] Reset button
    - [ ] Settings button
    - [ ] Check button
    - [ ] Hint button
    - [ ] Undo button
    - [ ] Draw button
    - [ ] Erase button
