### ISSUE TITLE
General art to-do list

### ISSUE THREAD

**Issue by Luke-Michael-Brown** [pfryerda/symbolize-android#4]
- [ ] Make game logo
- [ ] Make loading animation
- [ ] Make 'Studio++' animation
- [ ] Put color hex codes into res/valus/colors ( shared by game colour and line colours )
    - [ ] World 1 - Green
    - [ ] World 2 - Cyan
    - [ ] World 3 - Yellow
    - [ ] World 4 - Blue
    - [ ] World 5 -  Red
    - [ ] World 6 - Purple
    - [ ] World 7 - Black
